POST http://localhost:8080/users HTTP/1.1
content-Type: application/json

# {
#   "name": "nina",
#   "username": "nininha",
#   "email": "nina@mail.com",
#   "password": "nina1234"
# }

# {
#   "name": "vanagila",
#   "username": "vanagila",
#   "email": "vanagila@mail.com",
#   "password": "vanagila1234"
# }

# {
#   "name": "van",
#   "username": "van",
#   "email": "van@mail.com",
#   "password": "van12345"
# }

{
  "name": "usuario",
  "username": "usuario",
  "email": "usuario@mail.com",
  "password": "usuario1234"
}